// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_zindex_cpp
IntegerVector compute_zindex_cpp(IntegerVector x, IntegerVector y, IntegerVector z, int max_coord_bits);
RcppExport SEXP _fmriarrow_compute_zindex_cpp(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP max_coord_bitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type max_coord_bits(max_coord_bitsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_zindex_cpp(x, y, z, max_coord_bits));
    return rcpp_result_gen;
END_RCPP
}
// compute_hindex_cpp
SEXP compute_hindex_cpp(IntegerVector x, IntegerVector y, IntegerVector z, int nbits, bool as_character);
RcppExport SEXP _fmriarrow_compute_hindex_cpp(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP nbitsSEXP, SEXP as_characterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type nbits(nbitsSEXP);
    Rcpp::traits::input_parameter< bool >::type as_character(as_characterSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hindex_cpp(x, y, z, nbits, as_character));
    return rcpp_result_gen;
END_RCPP
}
// compute_hindex_cpp_inverse
DataFrame compute_hindex_cpp_inverse(CharacterVector index, int nbits);
RcppExport SEXP _fmriarrow_compute_hindex_cpp_inverse(SEXP indexSEXP, SEXP nbitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type nbits(nbitsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hindex_cpp_inverse(index, nbits));
    return rcpp_result_gen;
END_RCPP
}
// hilbert3D_single
SEXP hilbert3D_single(int x, int y, int z, int nbits, bool as_character);
RcppExport SEXP _fmriarrow_hilbert3D_single(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP nbitsSEXP, SEXP as_characterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type nbits(nbitsSEXP);
    Rcpp::traits::input_parameter< bool >::type as_character(as_characterSEXP);
    rcpp_result_gen = Rcpp::wrap(hilbert3D_single(x, y, z, nbits, as_character));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fmriarrow_compute_zindex_cpp", (DL_FUNC) &_fmriarrow_compute_zindex_cpp, 4},
    {"_fmriarrow_compute_hindex_cpp", (DL_FUNC) &_fmriarrow_compute_hindex_cpp, 5},
    {"_fmriarrow_compute_hindex_cpp_inverse", (DL_FUNC) &_fmriarrow_compute_hindex_cpp_inverse, 2},
    {"_fmriarrow_hilbert3D_single", (DL_FUNC) &_fmriarrow_hilbert3D_single, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fmriarrow(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
