// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_zindex_cpp
IntegerVector compute_zindex_cpp(IntegerVector x, IntegerVector y, IntegerVector z, int max_coord_bits);
RcppExport SEXP _fmriarrow_compute_zindex_cpp(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP max_coord_bitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type max_coord_bits(max_coord_bitsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_zindex_cpp(x, y, z, max_coord_bits));
    return rcpp_result_gen;
END_RCPP
}
// compute_hindex_cpp
Rcpp::NumericVector compute_hindex_cpp(Rcpp::IntegerVector x, Rcpp::IntegerVector y, Rcpp::IntegerVector z, int max_coord_bits);
RcppExport SEXP _fmriarrow_compute_hindex_cpp(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP max_coord_bitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type max_coord_bits(max_coord_bitsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hindex_cpp(x, y, z, max_coord_bits));
    return rcpp_result_gen;
END_RCPP
}
// compute_hindex_cpp_inverse
Rcpp::DataFrame compute_hindex_cpp_inverse(Rcpp::NumericVector h_indices, int max_coord_bits);
RcppExport SEXP _fmriarrow_compute_hindex_cpp_inverse(SEXP h_indicesSEXP, SEXP max_coord_bitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type h_indices(h_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type max_coord_bits(max_coord_bitsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hindex_cpp_inverse(h_indices, max_coord_bits));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fmriarrow_compute_zindex_cpp", (DL_FUNC) &_fmriarrow_compute_zindex_cpp, 4},
    {"_fmriarrow_compute_hindex_cpp", (DL_FUNC) &_fmriarrow_compute_hindex_cpp, 4},
    {"_fmriarrow_compute_hindex_cpp_inverse", (DL_FUNC) &_fmriarrow_compute_hindex_cpp_inverse, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fmriarrow(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
