# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_zindex_cpp <- function(x, y, z, max_coord_bits = 10L) {
    .Call(`_fmriarrow_compute_zindex_cpp`, x, y, z, max_coord_bits)
}

compute_hindex_cpp <- function(x, y, z, max_coord_bits) {
    .Call(`_fmriarrow_compute_hindex_cpp`, x, y, z, max_coord_bits)
}

compute_hindex_cpp_inverse <- function(h_indices, max_coord_bits) {
    .Call(`_fmriarrow_compute_hindex_cpp_inverse`, h_indices, max_coord_bits)
}

